"""add extracted_text to documents

Revision ID: 0e503332e8a9
Revises: c89341a12674
Create Date: 2026-01-13 11:11:45.818128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e503332e8a9'
down_revision = 'c89341a12674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('extracted_text')

    # ### end Alembic commands ###
