"""Add complete profile fields to User model

Revision ID: 92326996050b
Revises: 8623eb2ce69a
Create Date: 2025-12-24 22:23:47.939524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92326996050b'
down_revision = '8623eb2ce69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # REMOVED: Drop commands for apps and app_chat_reports tables
    # These tables contain existing data and should be preserved
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('business_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pincode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('notification_preference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('profile_completed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_completed')
        batch_op.drop_column('notification_preference')
        batch_op.drop_column('preferred_language')
        batch_op.drop_column('timezone')
        batch_op.drop_column('pincode')
        batch_op.drop_column('city')
        batch_op.drop_column('state')
        batch_op.drop_column('country')
        batch_op.drop_column('website_url')
        batch_op.drop_column('business_category')
        batch_op.drop_column('business_name')

    # REMOVED: Recreate commands for apps and app_chat_reports tables
    # Since we didn't drop them in upgrade(), we don't recreate them here
    # ### end Alembic commands ###
