"""add file_type and file_size to documents

Revision ID: c89341a12674
Revises: afd81b8bd2f1
Create Date: 2026-01-12 22:58:45.655936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89341a12674'
down_revision = 'afd81b8bd2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_type')

    # ### end Alembic commands ###
